"use client";

import { apiFetch, ensureSession, getSession } from "@/lib/authClient";
import { Check, Clock3, Crown, ExternalLink, UserPlus } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type Application = { id: string; full_name: string; email: string; phone?: string | null; tier_name: string; monthly_price: number; note?: string | null; status: string; payment_status: string };

export default function MembershipDesk() {
  const [items, setItems] = useState<Application[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [access, setAccess] = useState<Record<string, string>>({}); const [invite, setInvite] = useState({ code: "", label: "", tier: "vector_plus" }); const [inviteMessage, setInviteMessage] = useState("");
  async function load() { try { setItems(await apiFetch<Application[]>("/membership/applications")); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load membership applications."); } }
  useEffect(() => { void ensureSession().then(() => { const role = getSession()?.user.role; if (role === "operator" || role === "admin") void load(); else setError("Operator access is required."); }); }, []);
  async function enable(id: string) { setBusy(id); try { const result = await apiFetch<{ access_url: string }>(`/membership/applications/${id}/enable`, { method: "POST" }); setAccess((current) => ({ ...current, [id]: result.access_url })); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to enable this membership."); } finally { setBusy(null); } }
  async function createInvite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setInviteMessage(""); try { const result = await apiFetch<{ code: string }>("/membership/invite-keys", { method: "POST", body: JSON.stringify(invite) }); setInviteMessage(`Key ${result.code} is ready. Keep it in your private list; Vector stores only a secure fingerprint.`); setInvite({ code: "", label: "", tier: "vector_plus" }); } catch (caught) { setInviteMessage(caught instanceof Error ? caught.message : "Unable to create that invitation key."); } }
  return <div className="content membership-desk"><div className="page-heading"><div><p className="eyebrow">MEMBERSHIP DESK</p><h1>New introductions</h1><p>Review applications, confirm payment externally, then enable private access.</p></div><span className="partner-mode"><Crown size={15}/>{items.filter((item) => item.status !== "active").length} awaiting</span></div>{error && <div className="partner-message error">{error}</div>}<form className="panel membership-invite" onSubmit={createInvite}><p><b>Create complimentary invitation</b><small>Keep the code in your own list.</small></p><input value={invite.label} onChange={(e) => setInvite({ ...invite, label: e.target.value })} placeholder="Reference" required/><select value={invite.tier} onChange={(e) => setInvite({ ...invite, tier: e.target.value })}><option value="vector">Vector</option><option value="vector_plus">Vector Plus</option><option value="vector_prive">Vector Privé</option></select><input value={invite.code} onChange={(e) => setInvite({ ...invite, code: e.target.value.toUpperCase() })} placeholder="One-time key" required minLength={8}/><button>Create key</button>{inviteMessage && <small className="invite-message">{inviteMessage}</small>}</form><section className="panel membership-list">{items.length === 0 ? <div className="approval-empty"><UserPlus size={22}/><p>No membership applications yet.</p></div> : items.map((item) => <article key={item.id}><div className="membership-avatar">{item.full_name.split(" ").map((part) => part[0]).slice(0,2).join("")}</div><div><small>{item.tier_name} · £{item.monthly_price}/month</small><h2>{item.full_name}</h2><p>{item.email}{item.phone ? ` · ${item.phone}` : ""}</p>{item.note && <blockquote>“{item.note}”</blockquote>}</div><aside><span className={`membership-status ${item.status}`}>{item.status === "active" ? <Check size={13}/> : <Clock3 size={13}/>}{item.status.replaceAll("_", " ")}</span><small>{item.payment_status.replaceAll("_", " ")}</small>{item.status !== "active" ? <button onClick={() => enable(item.id)} disabled={busy === item.id}>{busy === item.id ? "Enabling…" : "Confirm & enable"}</button> : access[item.id] ? <a href={access[item.id]} target="_blank" rel="noreferrer">Access link <ExternalLink size={13}/></a> : null}</aside></article>)}</section></div>;
}
