"use client";

import { apiFetch, getSession } from "@/lib/authClient";
import { AlertTriangle, ArrowRight, Check, Clock3, Plane, Radar, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type RequestItem = { id: string; title: string; client_id: string };
type Alert = { id: string; level: "watch" | "action" | "resolved"; title: string; detail: string; proposedAction: string; approvalRequired: boolean };
type Journey = { id: string; request_id: string | null; client_id: string | null; title: string; status: "monitoring" | "attention" | "protected"; payload: { client?: string; route?: string; dates?: string; nextCheck?: string; signals?: string[]; alerts?: Alert[] } };

export default function TripGuardianPage() {
  const [journeys, setJourneys] = useState<Journey[]>([]);
  const [requests, setRequests] = useState<RequestItem[]>([]);
  const [message, setMessage] = useState("");
  const [creating, setCreating] = useState(false);
  const operator = ["operator", "admin"].includes(getSession()?.user.role || "");
  async function refresh() { try { const [storedJourneys, storedRequests] = await Promise.all([apiFetch<Journey[]>("/operations/journey"), apiFetch<RequestItem[]>("/requests")]); setJourneys(storedJourneys); setRequests(storedRequests); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load Trip Guardian."); } }
  useEffect(() => { refresh(); }, []);
  async function beginMonitoring() { const request = requests.find((item) => item.client_id); if (!request) { setMessage("Create a client request first, then Trip Guardian can monitor it."); return; } setCreating(true); try { await apiFetch("/operations/journey", { method: "POST", body: JSON.stringify({ client_id: request.client_id, request_id: request.id, title: request.title, status: "monitoring", payload: { route: "Journey details to be confirmed", dates: "Dates to be confirmed", nextCheck: "Set by operator", signals: ["Itinerary", "Supplier confirmation", "Critical deadlines"], alerts: [] } }) }); setMessage("Trip Guardian is now monitoring this request."); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not start monitoring."); } finally { setCreating(false); } }
  async function resolve(journey: Journey, alert: Alert) { try { const alerts = (journey.payload.alerts || []).map((item) => item.id === alert.id ? { ...item, level: "resolved" as const } : item); await apiFetch(`/operations/journey/${journey.id}`, { method: "PATCH", body: JSON.stringify({ status: "protected", payload: { ...journey.payload, alerts } }) }); setMessage("Intervention recorded in the shared service timeline."); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not record intervention."); } }
  return <div className="content guardian-page"><header className="guardian-hero"><div><p className="eyebrow">PROACTIVE PROTECTION</p><h1>Trip Guardian</h1><p>Monitor the journey, prepare the answer, ask only when judgement is needed.</p></div><aside><Radar/><div><b>{journeys.filter((item) => item.status === "attention").length} journeys need attention</b><span>{journeys.length} active journeys monitored</span></div></aside></header>{message && <div className="guardian-message"><Check/>{message}</div>}{!journeys.length && <div className="approval-empty"><p>No journeys are being monitored yet.</p>{operator && <button className="primary-button" disabled={creating} onClick={beginMonitoring}>{creating ? "Starting…" : "Start monitoring next request"}</button>}</div>}<div className="guardian-grid">{journeys.map((journey) => { const alerts = journey.payload.alerts || []; return <article key={journey.id} className={`guardian-card ${journey.status}`}><header><div><span><Plane/></span><div><small>{journey.payload.client || "Vector member"}</small><h2>{journey.payload.route || journey.title}</h2><p>{journey.payload.dates || "Dates to be confirmed"}</p></div></div><b>{journey.status}</b></header><div className="guardian-next"><Clock3/><span>Next automated check</span><b>{journey.payload.nextCheck || "Operator to set"}</b></div><div className="guardian-signals">{(journey.payload.signals || []).map((signal) => <span key={signal}><Radar/>{signal}</span>)}</div><div className="guardian-alerts">{alerts.length ? alerts.map((alert) => <section key={alert.id} className={alert.level}><div>{alert.level === "resolved" ? <ShieldCheck/> : <AlertTriangle/>}<span><strong>{alert.title}</strong><p>{alert.detail}</p></span></div><blockquote>{alert.proposedAction}</blockquote><footer><small>{alert.approvalRequired ? "Principal approval required" : "Within standing authority"}</small>{operator && alert.level !== "resolved" && <button onClick={() => resolve(journey, alert)}>Record intervention <ArrowRight/></button>}{alert.level === "resolved" && <b><Check/> Protected</b>}</footer></section>) : <p className="guardian-no-alerts">No current risks. The journey is being monitored.</p>}</div>{journey.request_id && <Link href={`/ops/requests?id=${journey.request_id}`}>Open request and proof timeline <ArrowRight/></Link>}</article>; })}</div></div>;
}
