export type RequestStatus = "new"|"triaged"|"in_progress"|"awaiting_approval"|"approved"|"confirmed";
export type RequestItem = { id:string; serverId?:string; client:string; initials:string; tier:string; title:string; message:string; category:string; urgency:"urgent"|"high"|"normal"; status:RequestStatus; channel:string; received:string; budget:string; confidence:number; owner:string; tags:string[]; draft:string; rationale:string[] };
export const requests: RequestItem[] = [
 {id:"VEC-1048",client:"Amelia Hart",initials:"AH",tier:"Signature Family",title:"Half-term in Kyoto",message:"Could you arrange Kyoto for the four of us, 24–31 October? Somewhere serene, connecting rooms, and the children would love a private ceramics class. Please avoid very formal hotels.",category:"Travel",urgency:"high",status:"awaiting_approval",channel:"WhatsApp",received:"12 min ago",budget:"£18,000–£25,000",confidence:94,owner:"Crispin",tags:["Family","Japan","School holiday"],draft:"Amelia — I’ve shaped this around a quieter Kyoto rather than a formal grand hotel. My recommendation is the riverside suite at Genji Kyoto, with connecting space held for 48 hours. I’ve also found a private studio session with a third-generation ceramicist. The estimated total is £21,840; I’ll send the concise comparison before anything is committed.",rationale:["Matches preference for intimate hotels","Family configuration confirmed","High-value trip requires approval"]},
 {id:"VEC-1047",client:"Marcus Chen",initials:"MC",tier:"Private",title:"Board dinner for eight",message:"Dinner in Mayfair tomorrow, eight people, quiet enough to talk. One pescatarian. 7.30 ideally.",category:"Dining",urgency:"urgent",status:"triaged",channel:"Email",received:"26 min ago",budget:"£1,500",confidence:88,owner:"Unassigned",tags:["Business","Quiet room","Pescatarian"],draft:"Marcus — I’m checking three discreet Mayfair options with quiet tables and strong pescatarian menus. I’ll return with one clear recommendation and two alternatives within 30 minutes.",rationale:["Time-sensitive booking","Known preference: understated service","No financial commitment yet"]},
 {id:"VEC-1046",client:"Sofia Rahman",initials:"SR",tier:"Family Office",title:"Heathrow transfer changed",message:"Flight now lands at 18:40. Please move the driver and make sure the child seat is still in the car.",category:"Transport",urgency:"urgent",status:"in_progress",channel:"WhatsApp",received:"41 min ago",budget:"£280",confidence:98,owner:"Elena",tags:["Flight change","Child seat"],draft:"Sofia — seen and being handled. I’m moving the driver to the new arrival time and reconfirming the child seat now.",rationale:["Existing verified supplier","No price change expected","Urgent acknowledgement sent"]},
 {id:"VEC-1045",client:"James Whitmore",initials:"JW",tier:"Private",title:"Monaco helicopter quote",message:"Can you book the quickest helicopter from Nice to Monaco after BA348 on Friday?",category:"Aviation",urgency:"normal",status:"awaiting_approval",channel:"Web",received:"1 hr ago",budget:"£3,200",confidence:72,owner:"Crispin",tags:["Specialist partner","Weather risk"],draft:"James — I have your arrival and am checking the safest workable connection with our specialist partner. I’ll confirm the baggage limits, transfer buffer and weather fallback before proposing the booking.",rationale:["Private aviation always escalates","Confidence below threshold","Specialist partner required"]},
 {id:"VEC-1044",client:"Amelia Hart",initials:"AH",tier:"Signature Family",title:"Anniversary flowers",message:"Peonies to the hotel room before we arrive next Thursday — soft colours, nothing too arranged.",category:"Lifestyle",urgency:"normal",status:"confirmed",channel:"WhatsApp",received:"Yesterday",budget:"£220",confidence:97,owner:"Elena",tags:["Anniversary","Preference learned"],draft:"All arranged — soft blush peonies will be placed in the room before arrival, naturally styled as requested.",rationale:["Verified hotel florist","Within standing authority","Preference saved"]}
];
export const clients = [
 {name:"Amelia Hart",initials:"AH",tier:"Signature Family",location:"London · GMT+1",requests:18,spend:"£84.2k",note:"Warm, informal service. Boutique hotels over grand properties.",prefs:["Connecting rooms","Aisle seats","No shellfish","Natural florals"]},
 {name:"Marcus Chen",initials:"MC",tier:"Private",location:"London / Singapore",requests:9,spend:"£31.8k",note:"Business hosting; values privacy and acoustic comfort.",prefs:["Quiet tables","Japanese cuisine","Late checkout"]},
 {name:"Sofia Rahman",initials:"SR",tier:"Family Office",location:"Dubai / London",requests:26,spend:"£142.6k",note:"Travels with two young children. Precise transfers are essential.",prefs:["Child seat","Halal dining","Meet & greet","Arabic speaker"]},
 {name:"James Whitmore",initials:"JW",tier:"Private",location:"Geneva · GMT+2",requests:7,spend:"£22.4k",note:"Fast-moving solo travel; wants the recommendation, not the search.",prefs:["Hand luggage","Early flights","Firm mattress"]}
];
