"use client";
import { apiFetch } from "@/lib/authClient";
import { Check, Pause, Play, ShieldCheck, UserRoundCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
type Client = { id: string; full_name: string; tier: string };
type Record = { id: string; title: string; status: string; payload: { delegate?: string; scopes?: string[]; spending_limit?: number; approval_rules?: string[] } };

export default function MandateWalletPage() {
  const [clients, setClients] = useState<Client[]>([]); const [items, setItems] = useState<Record[]>([]); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ client_id: "", delegate: "", scopes: "Flights, Hotels, Dining", spending_limit: "2500", approval_rules: "Non-refundable bookings" });
  async function load() { try { const [nextClients, nextItems] = await Promise.all([apiFetch<Client[]>("/clients"), apiFetch<Record[]>("/operations/mandate")]); setClients(nextClients); setItems(nextItems); setForm((current) => ({ ...current, client_id: current.client_id || nextClients[0]?.id || "" })); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load mandates."); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); try { await apiFetch("/operations/mandate", { method: "POST", body: JSON.stringify({ client_id: form.client_id, title: form.delegate, payload: { delegate: form.delegate, scopes: form.scopes.split(",").map((item) => item.trim()).filter(Boolean), spending_limit: Number(form.spending_limit), approval_rules: form.approval_rules.split(",").map((item) => item.trim()).filter(Boolean) } }) }); setForm((current) => ({ ...current, delegate: "" })); setMessage("Mandate recorded for the whole Vector team."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save mandate."); } }
  async function toggle(item: Record) { try { await apiFetch(`/operations/mandate/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: item.status === "active" ? "paused" : "active" }) }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update mandate."); } }
  return <div className="content mandate-page"><header className="mandate-hero"><div><p className="eyebrow">IDENTITY & AUTHORITY</p><h1>Mandate Wallet</h1><p>Shared authority records for principals, PAs and family-office delegates.</p></div><aside><ShieldCheck/><div><b>Authority lives outside the AI</b><span>Every change is retained centrally.</span></div></aside></header>{message && <div className="guardian-message"><Check/>{message}</div>}<form className="panel membership-invite" onSubmit={create}><p><b>Add a mandate</b><small>Use a named delegate and explicit boundaries.</small></p><select value={form.client_id} onChange={(event) => setForm({ ...form, client_id: event.target.value })} required>{clients.map((client) => <option key={client.id} value={client.id}>{client.full_name} · {client.tier}</option>)}</select><input value={form.delegate} onChange={(event) => setForm({ ...form, delegate: event.target.value })} placeholder="Delegate name" required/><input value={form.scopes} onChange={(event) => setForm({ ...form, scopes: event.target.value })} placeholder="Flights, Hotels, Dining" required/><input type="number" min="0" value={form.spending_limit} onChange={(event) => setForm({ ...form, spending_limit: event.target.value })} required/><input value={form.approval_rules} onChange={(event) => setForm({ ...form, approval_rules: event.target.value })} required/><button>Save mandate</button></form><section className="panel membership-list">{items.length ? items.map((item) => <article key={item.id}><div className="membership-avatar"><UserRoundCheck size={18}/></div><div><small>SHARED AUTHORITY RECORD</small><h2>{item.payload.delegate || item.title}</h2><p>May arrange: {(item.payload.scopes || []).join(" · ") || "Not specified"}</p><blockquote>Limit: £{Number(item.payload.spending_limit || 0).toLocaleString()} · Principal approval: {(item.payload.approval_rules || []).join("; ") || "Not specified"}</blockquote></div><aside><span className={`membership-status ${item.status}`}>{item.status}</span><button onClick={() => void toggle(item)}>{item.status === "active" ? <><Pause size={13}/> Pause</> : <><Play size={13}/> Activate</>}</button></aside></article>) : <div className="approval-empty"><ShieldCheck/><p>No mandates recorded yet. Add one before allowing a delegate to proceed.</p></div>}</section></div>;
}
